sudo: required
services:
  - docker

before_install:
  - docker build -t sapta94/myapp-test -f ./react-app-docker-integration/Dockerfile.dev .

script:
  - docker run -e CI=true sapta94/myapp-test npm run test

after_sucess:
  - docker build -t sapta94/multi-client -f ./react-app-docker-integration
  - docker build -t sapta94/multi-nginx -f ./nginx
  - docker build -t sapta94/multi-worker -f ./worker

  # log in to docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  
  #push images to docker hub
  - docker push sapta94/multi-client
  - docker push sapta94/multi-nginx
  - docker push sapta94/multi-worker
