sudo: required
services:
  - docker

before_install:
  - docker build -t sapta94/myapp-test -f ./react-app-docker-integration/Dockerfile.dev .

script:
  - docker run -e CI=true sapta94/myapp-test npm run test

after_sucess:
  - docker build -t sapta94/multi-client -f ./react-app-docker-integration
  - docker build -t sapta94/multi-nginx -f ./nginx
  - docker build -t sapta94/multi-worker -f ./worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-349772406588"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key: $AWS_SECRET_KEY
